package mx.edu.iems.inventario.model;

// Generated 14/05/2013 11:10:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Area generated by hbm2java
 */
public class Area implements java.io.Serializable {

	private int idarea;
	private String descripcion;
	private Set puestos = new HashSet(0);

	public Area() {
	}

	public Area(int idarea, String descripcion) {
		this.idarea = idarea;
		this.descripcion = descripcion;
	}

	public Area(int idarea, String descripcion, Set puestos) {
		this.idarea = idarea;
		this.descripcion = descripcion;
		this.puestos = puestos;
	}

	public int getIdarea() {
		return this.idarea;
	}

	public void setIdarea(int idarea) {
		this.idarea = idarea;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getPuestos() {
		return this.puestos;
	}

	public void setPuestos(Set puestos) {
		this.puestos = puestos;
	}

	@Override
	public String toString() {
		return descripcion;
	}

}
