package mx.edu.iems.inventario.model;

// Generated 14/05/2013 11:10:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Cpu generated by hbm2java
 */
public class Cpu implements java.io.Serializable {

	private int idcpu;
	private Tipocpu tipocpu;
	private Empleado empleado;
	private Estadoequipo estadoequipo;
	private Usuario usuario;
	private Ubicacion ubicacion;
	private String serie;
	private int progresivo;
	private String obervacion;
	private String fechaalta;
	private Set computadoras = new HashSet(0);

	public Cpu() {
	}

	public Cpu(int idcpu, Tipocpu tipocpu, Empleado empleado,
			Estadoequipo estadoequipo, Usuario usuario, Ubicacion ubicacion,
			String serie, int progresivo, String obervacion, String fechaalta) {
		this.idcpu = idcpu;
		this.tipocpu = tipocpu;
		this.empleado = empleado;
		this.estadoequipo = estadoequipo;
		this.usuario = usuario;
		this.ubicacion = ubicacion;
		this.serie = serie;
		this.progresivo = progresivo;
		this.obervacion = obervacion;
		this.fechaalta = fechaalta;
	}

	public Cpu(int idcpu, Tipocpu tipocpu, Empleado empleado,
			Estadoequipo estadoequipo, Usuario usuario, Ubicacion ubicacion,
			String serie, int progresivo, String obervacion, String fechaalta,
			Set computadoras) {
		this.idcpu = idcpu;
		this.tipocpu = tipocpu;
		this.empleado = empleado;
		this.estadoequipo = estadoequipo;
		this.usuario = usuario;
		this.ubicacion = ubicacion;
		this.serie = serie;
		this.progresivo = progresivo;
		this.obervacion = obervacion;
		this.fechaalta = fechaalta;
		this.computadoras = computadoras;
	}

	public int getIdcpu() {
		return this.idcpu;
	}

	public void setIdcpu(int idcpu) {
		this.idcpu = idcpu;
	}

	public Tipocpu getTipocpu() {
		return this.tipocpu;
	}

	public void setTipocpu(Tipocpu tipocpu) {
		this.tipocpu = tipocpu;
	}

	public Empleado getEmpleado() {
		return this.empleado;
	}

	public void setEmpleado(Empleado empleado) {
		this.empleado = empleado;
	}

	public Estadoequipo getEstadoequipo() {
		return this.estadoequipo;
	}

	public void setEstadoequipo(Estadoequipo estadoequipo) {
		this.estadoequipo = estadoequipo;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Ubicacion getUbicacion() {
		return this.ubicacion;
	}

	public void setUbicacion(Ubicacion ubicacion) {
		this.ubicacion = ubicacion;
	}

	public String getSerie() {
		return this.serie;
	}

	public void setSerie(String serie) {
		this.serie = serie;
	}

	public int getProgresivo() {
		return this.progresivo;
	}

	public void setProgresivo(int progresivo) {
		this.progresivo = progresivo;
	}

	public String getObervacion() {
		return this.obervacion;
	}

	public void setObervacion(String obervacion) {
		this.obervacion = obervacion;
	}

	public String getFechaalta() {
		return this.fechaalta;
	}

	public void setFechaalta(String fechaalta) {
		this.fechaalta = fechaalta;
	}

	public Set getComputadoras() {
		return this.computadoras;
	}

	public void setComputadoras(Set computadoras) {
		this.computadoras = computadoras;
	}

}
