package mx.edu.iems.inventario.model;

// Generated 14/05/2013 11:10:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado implements java.io.Serializable {

	private int idempleado;
	private Puesto puesto;
	private Usuario usuario;
	private boolean activo;
	private String apaterno;
	private String amaterno;
	private String nombre;
	private String fechaalta;
	private String fechanacimiento;
	private Set cpus = new HashSet(0);
	private Set nobreaks = new HashSet(0);
	private Set monitors = new HashSet(0);
	private Set computadoras = new HashSet(0);

	public Empleado() {
	}

	public Empleado(int idempleado, Puesto puesto, Usuario usuario,
			boolean activo, String apaterno, String amaterno, String nombre,
			String fechaalta, String fechanacimiento) {
		this.idempleado = idempleado;
		this.puesto = puesto;
		this.usuario = usuario;
		this.activo = activo;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
		this.nombre = nombre;
		this.fechaalta = fechaalta;
		this.fechanacimiento = fechanacimiento;
	}

	public Empleado(int idempleado, Puesto puesto, Usuario usuario,
			boolean activo, String apaterno, String amaterno, String nombre,
			String fechaalta, String fechanacimiento, Set cpus, Set nobreaks,
			Set monitors, Set computadoras) {
		this.idempleado = idempleado;
		this.puesto = puesto;
		this.usuario = usuario;
		this.activo = activo;
		this.apaterno = apaterno;
		this.amaterno = amaterno;
		this.nombre = nombre;
		this.fechaalta = fechaalta;
		this.fechanacimiento = fechanacimiento;
		this.cpus = cpus;
		this.nobreaks = nobreaks;
		this.monitors = monitors;
		this.computadoras = computadoras;
	}

	public int getIdempleado() {
		return this.idempleado;
	}

	public void setIdempleado(int idempleado) {
		this.idempleado = idempleado;
	}

	public Puesto getPuesto() {
		return this.puesto;
	}

	public void setPuesto(Puesto puesto) {
		this.puesto = puesto;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public boolean isActivo() {
		return this.activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	public String getApaterno() {
		return this.apaterno;
	}

	public void setApaterno(String apaterno) {
		this.apaterno = apaterno;
	}

	public String getAmaterno() {
		return this.amaterno;
	}

	public void setAmaterno(String amaterno) {
		this.amaterno = amaterno;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getFechaalta() {
		return this.fechaalta;
	}

	public void setFechaalta(String fechaalta) {
		this.fechaalta = fechaalta;
	}

	public String getFechanacimiento() {
		return this.fechanacimiento;
	}

	public void setFechanacimiento(String fechanacimiento) {
		this.fechanacimiento = fechanacimiento;
	}

	public Set getCpus() {
		return this.cpus;
	}

	public void setCpus(Set cpus) {
		this.cpus = cpus;
	}

	public Set getNobreaks() {
		return this.nobreaks;
	}

	public void setNobreaks(Set nobreaks) {
		this.nobreaks = nobreaks;
	}

	public Set getMonitors() {
		return this.monitors;
	}

	public void setMonitors(Set monitors) {
		this.monitors = monitors;
	}

	public Set getComputadoras() {
		return this.computadoras;
	}

	public void setComputadoras(Set computadoras) {
		this.computadoras = computadoras;
	}

}
