package mx.edu.iems.inventario.model;

// Generated 14/05/2013 11:10:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Estadoequipo generated by hbm2java
 */
public class Estadoequipo implements java.io.Serializable {

	private int idestadoequipo;
	private String descripcion;
	private Set nobreaks = new HashSet(0);
	private Set cpus = new HashSet(0);
	private Set monitors = new HashSet(0);

	public Estadoequipo() {
	}

	public Estadoequipo(int idestadoequipo, String descripcion) {
		this.idestadoequipo = idestadoequipo;
		this.descripcion = descripcion;
	}

	public Estadoequipo(int idestadoequipo, String descripcion, Set nobreaks,
			Set cpus, Set monitors) {
		this.idestadoequipo = idestadoequipo;
		this.descripcion = descripcion;
		this.nobreaks = nobreaks;
		this.cpus = cpus;
		this.monitors = monitors;
	}

	public int getIdestadoequipo() {
		return this.idestadoequipo;
	}

	public void setIdestadoequipo(int idestadoequipo) {
		this.idestadoequipo = idestadoequipo;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getNobreaks() {
		return this.nobreaks;
	}

	public void setNobreaks(Set nobreaks) {
		this.nobreaks = nobreaks;
	}

	public Set getCpus() {
		return this.cpus;
	}

	public void setCpus(Set cpus) {
		this.cpus = cpus;
	}

	public Set getMonitors() {
		return this.monitors;
	}

	public void setMonitors(Set monitors) {
		this.monitors = monitors;
	}

}
