package mx.edu.iems.inventario.model;

// Generated 14/05/2013 11:10:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Puesto generated by hbm2java
 */
public class Puesto implements java.io.Serializable {

	private int idpuesto;
	private Area area;
	private String descripcion;
	private Set empleados = new HashSet(0);

	public Puesto() {
	}

	public Puesto(int idpuesto, Area area, String descripcion) {
		this.idpuesto = idpuesto;
		this.area = area;
		this.descripcion = descripcion;
	}

	public Puesto(int idpuesto, Area area, String descripcion, Set empleados) {
		this.idpuesto = idpuesto;
		this.area = area;
		this.descripcion = descripcion;
		this.empleados = empleados;
	}

	public int getIdpuesto() {
		return this.idpuesto;
	}

	public void setIdpuesto(int idpuesto) {
		this.idpuesto = idpuesto;
	}

	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

}
