package mx.edu.iems.inventario.model;

// Generated 14/05/2013 11:10:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tipomonitor generated by hbm2java
 */
public class Tipomonitor implements java.io.Serializable {

	private int idtipomonitor;
	private String marca;
	private String modelo;
	private String observacion;
	private Set monitors = new HashSet(0);

	public Tipomonitor() {
	}

	public Tipomonitor(int idtipomonitor, String marca, String modelo,
			String observacion) {
		this.idtipomonitor = idtipomonitor;
		this.marca = marca;
		this.modelo = modelo;
		this.observacion = observacion;
	}

	public Tipomonitor(int idtipomonitor, String marca, String modelo,
			String observacion, Set monitors) {
		this.idtipomonitor = idtipomonitor;
		this.marca = marca;
		this.modelo = modelo;
		this.observacion = observacion;
		this.monitors = monitors;
	}

	public int getIdtipomonitor() {
		return this.idtipomonitor;
	}

	public void setIdtipomonitor(int idtipomonitor) {
		this.idtipomonitor = idtipomonitor;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Set getMonitors() {
		return this.monitors;
	}

	public void setMonitors(Set monitors) {
		this.monitors = monitors;
	}

}
