package mx.edu.iems.inventario.model;

// Generated 14/05/2013 11:10:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Tiponobreak generated by hbm2java
 */
public class Tiponobreak implements java.io.Serializable {

	private int idtiponobreak;
	private String marca;
	private String modelo;
	private String observacion;
	private Set nobreaks = new HashSet(0);

	public Tiponobreak() {
	}

	public Tiponobreak(int idtiponobreak, String marca, String modelo,
			String observacion) {
		this.idtiponobreak = idtiponobreak;
		this.marca = marca;
		this.modelo = modelo;
		this.observacion = observacion;
	}

	public Tiponobreak(int idtiponobreak, String marca, String modelo,
			String observacion, Set nobreaks) {
		this.idtiponobreak = idtiponobreak;
		this.marca = marca;
		this.modelo = modelo;
		this.observacion = observacion;
		this.nobreaks = nobreaks;
	}

	public int getIdtiponobreak() {
		return this.idtiponobreak;
	}

	public void setIdtiponobreak(int idtiponobreak) {
		this.idtiponobreak = idtiponobreak;
	}

	public String getMarca() {
		return this.marca;
	}

	public void setMarca(String marca) {
		this.marca = marca;
	}

	public String getModelo() {
		return this.modelo;
	}

	public void setModelo(String modelo) {
		this.modelo = modelo;
	}

	public String getObservacion() {
		return this.observacion;
	}

	public void setObservacion(String observacion) {
		this.observacion = observacion;
	}

	public Set getNobreaks() {
		return this.nobreaks;
	}

	public void setNobreaks(Set nobreaks) {
		this.nobreaks = nobreaks;
	}

}
