package mx.edu.iems.inventario.model;

// Generated 14/05/2013 11:10:50 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private int idusuario;
	private String login;
	private String password;
	private boolean esadministrador;
	private Set cpus = new HashSet(0);
	private Set monitors = new HashSet(0);
	private Set empleados = new HashSet(0);
	private Set computadoras = new HashSet(0);
	private Set nobreaks = new HashSet(0);

	public Usuario() {
	}

	public Usuario(int idusuario, String login, String password,
			boolean esadministrador) {
		this.idusuario = idusuario;
		this.login = login;
		this.password = password;
		this.esadministrador = esadministrador;
	}

	public Usuario(int idusuario, String login, String password,
			boolean esadministrador, Set cpus, Set monitors, Set empleados,
			Set computadoras, Set nobreaks) {
		this.idusuario = idusuario;
		this.login = login;
		this.password = password;
		this.esadministrador = esadministrador;
		this.cpus = cpus;
		this.monitors = monitors;
		this.empleados = empleados;
		this.computadoras = computadoras;
		this.nobreaks = nobreaks;
	}

	public int getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(int idusuario) {
		this.idusuario = idusuario;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public boolean isEsadministrador() {
		return this.esadministrador;
	}

	public void setEsadministrador(boolean esadministrador) {
		this.esadministrador = esadministrador;
	}

	public Set getCpus() {
		return this.cpus;
	}

	public void setCpus(Set cpus) {
		this.cpus = cpus;
	}

	public Set getMonitors() {
		return this.monitors;
	}

	public void setMonitors(Set monitors) {
		this.monitors = monitors;
	}

	public Set getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Set empleados) {
		this.empleados = empleados;
	}

	public Set getComputadoras() {
		return this.computadoras;
	}

	public void setComputadoras(Set computadoras) {
		this.computadoras = computadoras;
	}

	public Set getNobreaks() {
		return this.nobreaks;
	}

	public void setNobreaks(Set nobreaks) {
		this.nobreaks = nobreaks;
	}

}
